### ISSUE TITLE
Devise Gem for Authentification?

### ISSUE THREAD

**Issue by achmiral** [neume/posko#11]
Hi, I'm curious why you did not use devise gem to handle authentication?

**Comment by neume** [comment]
I haven't figured it out yet to make it work with my current setup. Devise defaults require 1 unique identifier only. I need two of those.

These are the fields I need to authenticate a user:
+ Account ID - A unique identifier of each account.
+ Email - A unique identifier of each user in an account.
+ Password

This setup enables an email address to be linked on multiple accounts with different credentials
