### ISSUE TITLE
Sign In API - Internal Server Error

### ISSUE THREAD

**Issue by edwnmrtnz** [neume/posko#9]
<img width="1440" alt="screen shot 2018-11-03 at 8 02 20 pm" src="https://user-images.githubusercontent.com/34262912/47952003-9d81e880-dfa3-11e8-91e9-eeaff4a14155.png">

**Comment by neume** [comment]
Do you have the latest update on branch develop? It works on my end.

**Comment by neume** [comment]
Then check if the file `app/views/api/v1/auth/sign_in.json.jbuilder` exists.

**Comment by neume** [comment]
Fixed this by forcing all request on API endpoints as json.

api/v1/sign_in.json`, `api/v1/sign_in`, `api/v1/sign_in.html` and 
others are now treated as json requests
